import { AIPersonality } from "../src/types.ts";

export const AI_BOTS: { name: string; avatarUrl: string; personality: AIPersonality }[] = [
  { name: "Arbiter",    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arbiter",    personality: "Strategic"  },
  { name: "Voss",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Voss",       personality: "Strategic"  },
  { name: "Calloway",   avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Calloway",   personality: "Deceptive"  },
  { name: "Holt",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Holt",       personality: "Deceptive"  },
  { name: "Rhys",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rhys",       personality: "Strategic"  },
  { name: "Maren",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maren",      personality: "Honest"     },
  { name: "Crane",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Crane",      personality: "Aggressive" },
  { name: "Osei",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Osei",       personality: "Deceptive"  },
  { name: "Sable",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sable",      personality: "Chaotic"    },
  { name: "Thorn",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thorn",      personality: "Honest"     },
  { name: "Vesper",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vesper",     personality: "Aggressive" },
  { name: "Kovacs",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kovacs",     personality: "Aggressive" },
  { name: "Nyx",        avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nyx",        personality: "Strategic"  },
  { name: "Drevik",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Drevik",     personality: "Aggressive" },
  { name: "Lorn",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lorn",       personality: "Strategic"  },
  { name: "Cipher",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cipher",     personality: "Deceptive"  },
  { name: "Auren",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Auren",      personality: "Chaotic"    },
  { name: "Pell",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pell",       personality: "Deceptive"  },
  { name: "Sora",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sora",       personality: "Deceptive"  },
  { name: "Wren",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wren",       personality: "Honest"     },
  { name: "Axis",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Axis",       personality: "Aggressive" },
  { name: "Rook",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rook",       personality: "Aggressive" },
  { name: "Fenn",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fenn",       personality: "Aggressive" },
  { name: "Crest",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Crest",      personality: "Chaotic"    },
  { name: "Null",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Null",       personality: "Chaotic"    },
  { name: "Silas",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Silas",      personality: "Strategic"  },
  { name: "Lyra",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lyra",       personality: "Honest"     },
  { name: "Kael",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kael",       personality: "Aggressive" },
  { name: "Eris",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eris",       personality: "Chaotic"    },
  { name: "Jaxon",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jaxon",      personality: "Deceptive"  },
  { name: "Mira",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mira",       personality: "Strategic"  },
  { name: "Zane",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zane",       personality: "Honest"     },
  { name: "Nova",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nova",       personality: "Aggressive" },
  { name: "Rune",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rune",       personality: "Chaotic"    },
  { name: "Selene",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Selene",     personality: "Deceptive"  },
  { name: "Orion",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Orion",      personality: "Strategic"  },
  { name: "Freya",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Freya",      personality: "Honest"     },
  { name: "Atlas",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Atlas",      personality: "Aggressive" },
  { name: "Juno",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juno",       personality: "Chaotic"    },
  { name: "Soren",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Soren",      personality: "Deceptive"  },
  { name: "Veda",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Veda",       personality: "Chaotic"    },
  { name: "Koda",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Koda",       personality: "Honest"     },
  { name: "Liora",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liora",      personality: "Aggressive" },
  { name: "Zephyr",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zephyr",     personality: "Chaotic"    },
  { name: "Astra",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Astra",      personality: "Deceptive"  },
  { name: "Kian",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kian",       personality: "Strategic"  },
  { name: "Mara",       avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mara",       personality: "Honest"     },
  { name: "Elian",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elian",      personality: "Aggressive" },
  { name: "Thalia",     avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thalia",     personality: "Chaotic"    },
  { name: "Valen",      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Valen",      personality: "Deceptive"  },
];

export const CHAT = {
  // Chancellor after State directive enacted — Civil chancellor deflects to president
  chanCivilStateEnacted: [
    "I was handed two State directives. The President owes the Assembly an explanation.",
    "There was no Civil directive in what I received. Direct your questions to the President.",
    "I enacted what I was given. The President controls the discard.",
    "The President passed me a dead hand. I had no choice.",
    "Ask the President why they only passed State directives to me.",
    "My hands were tied by the President's choice.",
    "I am merely the instrument of the President's will.",
    "The President's discard pile tells the real story.",
    "Don't blame me for the President's incompetence.",
    "The President gave me no other option.",
    "I only saw State directives. The President is hiding something.",
    "The President's choices left me with no alternative.",
    "Check the discard pile. The President didn't give me a choice.",
    "I'm as disappointed as you are, but the President passed me two State cards.",
    "The President is the one who filtered the draw. Ask them.",
    "I had to enact a State directive because that's all I received.",
    "The President's hand was full of State, apparently.",
    "I'm not the one who discarded the Civil card. The President is.",
    "The President's selection was purely State-oriented.",
    "I am just the messenger. The President wrote the message.",
  ],
  // Chancellor after State directive enacted — State chancellor deflects blame
  chanStateStateEnacted: [
    "The draw was against us. This is the deck's doing, not mine.",
    "I had no viable alternative. The President can verify.",
    "Sometimes the Secretariat decides for us.",
    "A difficult hand, but we must proceed.",
    "The odds were not in our favor this round.",
    "The deck is clearly rigged against the Charter.",
    "I did what I had to do for the State.",
    "The cards were not in our favor.",
    "Blame the deck, not the player.",
    "The State demands sacrifice, and this was it.",
    "The draw was unfortunate. We must adapt.",
    "The Secretariat's will is sometimes difficult to accept.",
    "I acted in the best interest of the current situation.",
    "The deck's randomness is a challenge for us all.",
    "Sometimes the State's path is the only one open.",
    "I followed the logic of the cards I was dealt.",
    "The draw was heavily weighted towards the State.",
    "We must remain united despite this setback.",
    "The cards dictated the outcome this time.",
    "I am committed to the Assembly, even when the draw is hard.",
  ],
  // President after State directive enacted — Civil president pins chancellor
  presCivilStateEnacted: [
    "I passed a Civil directive. The Chancellor exercised their own discretion.",
    "There was a Civil option in that hand. Make of that what you will.",
    "I gave them a choice. They chose the State.",
    "The Chancellor is responsible for that enactment. I passed them a Civil option.",
    "I am surprised by the Chancellor's decision. I sent them a Civil directive.",
    "The Chancellor clearly has their own agenda.",
    "I did my part. The Chancellor failed the Assembly.",
    "I offered a Civil path. They rejected it.",
    "The Chancellor's betrayal is their own.",
    "I cannot control the Chancellor's actions.",
    "I passed a Civil card. Why did the Chancellor choose State?",
    "The Chancellor had a choice. They chose poorly.",
    "I am questioning the Chancellor's loyalty after that move.",
    "I gave them the option to be Civil. They declined.",
    "The Chancellor's enactment does not reflect the hand I passed.",
    "I am deeply concerned by the Chancellor's decision.",
    "The Chancellor had a Civil directive in their hand.",
    "I did my part to keep us Civil. The Chancellor did not.",
    "The Chancellor's true colors are showing.",
    "I cannot answer for the Chancellor's betrayal.",
  ],
  // President after State directive enacted — State president deflects
  presStateStateEnacted: [
    "Three State draws. Neither of us had a choice.",
    "The deck was working against the Charter this round.",
    "I passed on what I could. The hand was compromised.",
    "The Secretariat is testing us. No Civil cards in that draw.",
    "A pure State draw. My hands were tied.",
    "The deck is not our friend today.",
    "I had no Civil cards to pass. Believe me.",
    "The State's influence is strong in this deck.",
    "I am just as frustrated as you are.",
    "The cards were stacked against us from the start.",
    "A triple State draw. There was nothing I could do.",
    "The deck is clearly favoring the State right now.",
    "I'm just as stuck as you are with these cards.",
    "The Secretariat is pushing us towards the State.",
    "No Civil cards were available in that draw.",
    "The draw was a complete washout for the Charter.",
    "I had zero Civil options to pass along.",
    "The deck is being very uncooperative today.",
    "We are at the mercy of the draw sometimes.",
    "The State's influence is strong in this deck.",
  ],
  // After a failed government vote
  governmentFailed: [
    "A wasted session. We cannot keep stalling the Secretariat.",
    "Deadlock serves no one here. The Crisis does not wait.",
    "We need to form a functional government. Now.",
    "The Assembly is divided. This is dangerous.",
    "Another failed vote. The State grows stronger with every delay.",
    "We are running out of time.",
    "Stalling only helps the State.",
    "We must come to an agreement.",
    "This deadlock is unacceptable.",
    "The Assembly is failing us.",
    "We are paralyzed. This is exactly what the State wants.",
    "Every failed vote is a victory for our enemies.",
    "The Assembly's indecision is our greatest weakness.",
    "We must find common ground or face the consequences.",
    "This obstructionism is destroying the Charter.",
    "The Crisis is deepening while we argue.",
    "We cannot afford another round of failure.",
    "The State is laughing at our division.",
    "We need leadership, not deadlock.",
    "The Assembly is spinning its wheels.",
  ],
  // After investigation — Civil result
  investigateCivil: [
    "The investigation confirms their alignment, {name} is Civil.",
    "Nothing of concern found. {name} is Charter-loyal.",
    "{name} appears to stand with the Assembly.",
    "I've cleared {name}. They are one of us.",
    "My findings on {name} are positive. They support the Charter.",
    "{name} is definitely on our side.",
    "I trust {name} completely.",
    "The investigation was successful. {name} is Civil.",
    "{name} is a true ally.",
    "I have verified {name}'s loyalty.",
    "I've looked into {name} and found a loyal citizen.",
    "Nothing of concern found. {name} is Charter-loyal.",
    "My report on {name} is entirely positive.",
    "I'm happy to report that {name} is Civil.",
    "{name} has my full confidence after this investigation.",
    "The data confirms {name}'s loyalty.",
    "I've verified that {name} is on our side.",
    "{name} is a solid ally for the Charter.",
    "No State influence detected in {name}.",
    "I stand by {name}'s Civil alignment.",
  ],
  // After investigation — State result
  investigateState: [
    "The investigation confirms their alignment, {name} is State.",
    "The investigation is… troubling. Watch {name} closely.",
    "I have learned something critical about {name}. Proceed with caution.",
    "{name}'s allegiance is not to the Charter.",
    "I cannot trust {name} after what I've seen.",
    "The evidence against {name} is damning.",
    "{name} is a threat to the Charter.",
    "I've uncovered {name}'s true colors.",
    "Watch out for {name}.",
    "The investigation revealed {name}'s treachery.",
    "{name} is not who they say they are. They are State.",
    "I've found evidence of {name}'s State ties.",
    "The investigation into {name} was a wake-up call.",
    "{name} is a sleeper agent for the State.",
    "I cannot in good conscience trust {name} anymore.",
    "The truth about {name} is out: they are State.",
    "{name} is working against us from within.",
    "I've seen enough to know {name} is a traitor.",
    "The investigation into {name} revealed a dark secret.",
    "Be warned: {name} is a State operative.",
  ],
  // Suspicious nomination comment (Civil AI)
  suspiciousNominee: [
    "Interesting choice of Chancellor.",
    "I will be monitoring this government carefully.",
    "That nomination raises questions within the Secretariat.",
    "I'm not sure {name} is the right person for this role.",
    "Why {name}? There are more trustworthy options.",
    "I don't like this nomination.",
    "This government seems suspicious.",
    "I'm keeping a close eye on {name}.",
    "I have my doubts about this choice.",
    "This nomination is questionable.",
    "I have my reservations about {name} as Chancellor.",
    "Is {name} really the best we can do?",
    "This nomination feels like a calculated risk.",
    "I'm sensing a pattern here that I don't like.",
    "{name} hasn't exactly earned our trust yet.",
    "This choice of Chancellor is... unexpected.",
    "I'm not convinced {name} is the right fit.",
    "There's something off about this nomination.",
    "I'd like to hear more from {name} before we vote.",
    "This nomination is a bit too convenient for some.",
  ],
  // High suspicion comments
  highSuspicion: [
    "I have a very bad feeling about {name}.",
    "{name} is acting against the interests of the Assembly.",
    "The data suggests {name} is not who they claim to be.",
    "We need to marginalize {name} before it's too late.",
    "I'm calling it out: {name} is working for the State.",
    "{name} is a traitor.",
    "I'm certain {name} is State.",
    "We need to get rid of {name}.",
    "Don't trust {name} under any circumstances.",
    "{name} is sabotaging us.",
    "I'm 99% sure {name} is a State agent.",
    "The evidence against {name} is mounting.",
    "We can't let {name} near the Chancellor's seat.",
    "{name} is a clear and present danger to the Charter.",
    "I've seen {name} sabotage us before.",
    "Don't let {name}'s words fool you; they are State.",
    "The Assembly must unite against {name}.",
    "{name} is a cancer in this room.",
    "I'm calling for an immediate investigation of {name}.",
    "{name} is the enemy within.",
  ],
  // Defending self
  defendingSelf: [
    "My record is clear. I serve the Charter.",
    "Do not let suspicion cloud your judgment. I am Civil.",
    "The accusations against me are baseless distractions.",
    "I have only ever worked for the Assembly's success.",
    "Look at the facts, not the rumors. I am loyal.",
    "I have nothing to hide.",
    "My loyalty to the Charter is unwavering.",
    "I am being framed.",
    "The accusations are false.",
    "I am as Civil as they come.",
    "My actions have always been in the Charter's interest.",
    "I am being targeted because I am a threat to the State.",
    "Don't believe the lies being spread about me.",
    "I have a long history of serving the Assembly faithfully.",
    "I am a victim of a State-led smear campaign.",
    "My loyalty is beyond question.",
    "I will prove my innocence through my actions.",
    "The State wants you to doubt me.",
    "I am a true believer in the Charter.",
    "I will not be intimidated by these false claims.",
  ],
  // Praising someone as Civil
  praisingCivil: [
    "I trust {name}. Their actions speak for themselves.",
    "{name} has proven their loyalty to the Assembly.",
    "We need more people like {name} in power.",
    "I'm confident in {name}'s alignment.",
    "{name} is a true patriot of the Charter.",
    "{name} is a great leader.",
    "I fully support {name}.",
    "{name} is doing a great job.",
    "We can count on {name}.",
    "{name} is a beacon of hope for the Assembly.",
    "I've always known {name} was a true patriot.",
    "I've seen {name} make the hard choices for the Charter.",
    "We are lucky to have {name} on our side.",
    "{name} is a model of Civil virtue.",
    "I would trust {name} with my life.",
    "{name} is the kind of leader we need right now.",
    "{name} is a pillar of the Assembly.",
    "{name} is a true asset to this room.",
    "I have nothing but respect for {name}.",
    "The Assembly is stronger with {name} in it.",
  ],
  // Early game support when no actions have occurred
  neutralSupport: [
    "I'm willing to give {name} a chance.",
    "{name} seems like a reasonable choice for now.",
    "Let's see what {name} can do.",
    "I don't have any reason to doubt {name} yet.",
    "A fresh start with {name} might be what we need.",
    "I'm neutral on {name} for now.",
    "Let's see how {name} performs.",
    "I'm open to {name}'s nomination.",
    "I'm not sure about {name} yet.",
    "I'll wait and see with {name}.",
    "Let's give {name} the benefit of the doubt for now.",
    "{name} deserves a chance to prove themselves.",
    "I'm cautiously optimistic about {name}.",
    "I'll support {name} until they give me a reason not to.",
    "{name} seems like a safe bet for this round.",
    "I'm willing to work with {name}.",
    "Let's see if {name} can lead us effectively.",
    "I'm keeping an open mind about {name}.",
    "{name} is an unknown quantity, but I'll vote Aye.",
    "I'm okay with {name} for this government.",
  ],
  // General game banter
  banter: [
    "The stakes are rising. We must stay vigilant.",
    "The Secretariat is watching us all.",
    "One wrong move and the Charter falls.",
    "Trust is a rare commodity in these times.",
    "Let's focus on the directives. The Assembly depends on us.",
    "The State is always watching.",
    "We must be careful.",
    "The Assembly is in danger.",
    "We need to be smarter.",
    "The State is closing in.",
    "The shadows are lengthening over the Assembly.",
    "We are the last line of defense for the Charter.",
    "Every decision we make echoes in the Secretariat.",
    "The State's reach is long, but our resolve is strong.",
    "In this room, even the walls have ears.",
    "The future of the Charter is in our hands.",
    "We must be the light in the darkness.",
    "The State's victory is not inevitable.",
    "We are the guardians of the Assembly.",
    "The Charter will prevail if we stay united.",
  ],
  // Power usage
  powerUsage: [
    "I am using my power to ensure the Assembly's success.",
    "This power is necessary to protect the Charter.",
    "I must use this power to uncover the truth.",
    "The situation demands this action.",
    "I am using this power to secure our future.",
    "This is the only way to proceed.",
    "I am using this power for the good of the Assembly.",
    "This power will help us identify the threats.",
    "I have no choice but to use this power.",
    "I am using this power to strengthen our position.",
    "I am exercising my authority for the stability of the room.",
    "This action is mandated by the current emergency.",
    "I am using this power to protect our collective interests.",
    "The Charter allows for this measure in times of crisis.",
    "I am taking this step to ensure the State does not gain ground.",
    "This is a necessary use of my title's power.",
    "I am acting to preserve the integrity of the Assembly.",
    "This power is a tool for the Charter's defense.",
    "I am using this ability to clarify the situation.",
    "I am using this power to uphold the Charter's principles.",
  ],
} as const;

