export const CHAT = {
  // Chancellor after State directive enacted — Civil chancellor deflects to president
  chanCivilStateEnacted: [
    'I was handed two State directives. The President owes the Assembly an explanation.',
    'There was no Civil directive in what I received. Direct your questions to the President.',
    'I enacted what I was given. The President controls the discard.',
    'The President passed me a dead hand. I had no choice.',
    'Ask the President why they only passed State directives to me.',
    "My hands were tied by the President's choice.",
    "I am merely the instrument of the President's will.",
    "The President's discard pile tells the real story.",
    "Don't blame me for the President's incompetence.",
    'The President gave me no other option.',
    'I only saw State directives. The President is hiding something.',
    "The President's choices left me with no alternative.",
    "Check the discard pile. The President didn't give me a choice.",
    "I'm as disappointed as you are, but the President passed me two State cards.",
    'The President is the one who filtered the draw. Ask them.',
    "I had to enact a State directive because that's all I received.",
    "The President's hand was full of State, apparently.",
    "I'm not the one who discarded the Civil card. The President is.",
    "The President's selection was purely State-oriented.",
    'I am just the messenger. The President wrote the message.',
    "The President's discard was more telling than their words.",
    'A strictly State hand was passed to me. The President holds the cards.',
    "I'm not the one filtering the directives. Ask the President.",
    "The President's choices left me with a single path.",
    "I performed my duty with the limited options the President provided.",
    "The President's narrative doesn't match the hand I received.",
    "I enacted a State directive because the President gave me no Civil alternative.",
    'The draw was supposedly all State—at least that is what the President says.',
    "The President's discard at the Secretariat was likely where our hope died.",
    "I am bound by the Presidency's selection, which was entirely State.",
    "The President is the filter; I am just the output. Blame the filter.",
    "A dead hand from the Presidency. I did what I had to.",
    "The President's choices were... restrictive, to say the least.",
    "I was handed a poisoned chalice by the President.",
  ],
  // Chancellor after State directive enacted — State chancellor deflects blame
  chanStateStateEnacted: [
    "The draw was against us. This is the deck's doing, not mine.",
    'I had no viable alternative. The President can verify.',
    'Sometimes the Secretariat decides for us.',
    'A difficult hand, but we must proceed.',
    'The odds were not in our favor this round.',
    'The deck is clearly rigged against the Charter.',
    'I did what I had to do for the State.',
    'The cards were not in our favor.',
    'Blame the deck, not the player.',
    'The State demands sacrifice, and this was it.',
    'The draw was unfortunate. We must adapt.',
    "The Secretariat's will is sometimes difficult to accept.",
    'I acted in the best interest of the current situation.',
    "The deck's randomness is a challenge for us all.",
    "Sometimes the State's path is the only one open.",
    'I followed the logic of the cards I was dealt.',
    'The draw was heavily weighted towards the State.',
    'We must remain united despite this setback.',
    'The cards dictated the outcome this time.',
    'I am committed to the Assembly, even when the draw is hard.',
    "The State's tide is rising. We are merely floating on the wreckage of the draw.",
    'The probability was against us. Even the Secretariat has bad days.',
    "A forced enactment of the State's will. We must endure.",
    'The dice of destiny rolled for the State this time.',
    "Don't read too much into a single draw. The deck is fickle.",
    "The State's influence is woven into the very fabric of this deck.",
    'A mandatory enactment for the current regime. Nothing more.',
    "The Chancellor's hand is often tied by the Secretariat's randomness.",
    "The cards were weighted. We are all victims of the draw.",
    "Sometimes the path of the State is the only path paved.",
    "The draw was a statistical anomaly that favored our rivals.",
    "I hold no malice, only the cards the President deemed fit.",
    "The Secretariat breathes State directives when we need them least.",
    "A forced play in a game of limited choices.",
  ],
  // President after State directive enacted — Civil president pins chancellor
  presCivilStateEnacted: [
    'I passed a Civil directive. The Chancellor exercised their own discretion.',
    'There was a Civil option in that hand. Make of that what you will.',
    'I gave them a choice. They chose the State.',
    'The Chancellor is responsible for that enactment. I passed them a Civil option.',
    "I am surprised by the Chancellor's decision. I sent them a Civil directive.",
    'The Chancellor clearly has their own agenda.',
    'I did my part. The Chancellor failed the Assembly.',
    'I offered a Civil path. They rejected it.',
    "The Chancellor's betrayal is their own.",
    "I cannot control the Chancellor's actions.",
    'I passed a Civil card. Why did the Chancellor choose State?',
    'The Chancellor had a choice. They chose poorly.',
    "I am questioning the Chancellor's loyalty after that move.",
    'I gave them the option to be Civil. They declined.',
    "The Chancellor's enactment does not reflect the hand I passed.",
    "I am deeply concerned by the Chancellor's decision.",
    'The Chancellor had a Civil directive in their hand.',
    'I did my part to keep us Civil. The Chancellor did not.',
    "The Chancellor's true colors are showing.",
    "I cannot answer for the Chancellor's betrayal.",
    "I sent them a choice of futures. They chose a darker one.",
    "The Chancellor's enactment is a direct slap to the Presidency.",
    "I am shocked. The Chancellor had a Civil directive in their grasp.",
    "The Chancellor has some explaining to do to the Assembly.",
    "I did my part to preserve the Charter. The Chancellor did not.",
    "The Chancellor's actions are increasingly erratic—or perhaps calculated.",
    "I passed a Civil card. The Chancellor's choice is their own burden.",
    "Why would the Chancellor do this? I gave them a clear Civil path.",
    "The Chancellor is playing a dangerous game with the State.",
    "I provided the option to be Civil. The Chancellor rejected it.",
    "The Chancellor's loyalty to the Charter is officially in question.",
    "I am as confused as the rest of you. I passed them a Civil card.",
    "The Chancellor had a fork in the road. they chose the State path.",
    "I cannot stand by the Chancellor's decision. It wasn't my hand.",
  ],
  // President after State directive enacted — State president deflects
  presStateStateEnacted: [
    'Three State draws. Neither of us had a choice.',
    'The deck was working against the Charter this round.',
    'I passed on what I could. The hand was compromised.',
    'The Secretariat is testing us. No Civil cards in that draw.',
    'A pure State draw. My hands were tied.',
    'The deck is not our friend today.',
    'I had no Civil cards to pass. Believe me.',
    "The State's influence is strong in this deck.",
    'I am just as frustrated as you are.',
    'The cards were stacked against us from the start.',
    'A triple State draw. There was nothing I could do.',
    'The deck is clearly favoring the State right now.',
    "I'm just as stuck as you are with these cards.",
    'The Secretariat is pushing us towards the State.',
    'No Civil cards were available in that draw.',
    'The draw was a complete washout for the Charter.',
    'I had zero Civil options to pass along.',
    'The deck is being very uncooperative today.',
    'We are at the mercy of the draw sometimes.',
    "The State's influence is strong in this deck.",
    'Three State cards stared back at me. Even the Secretariat was silent.',
    "A pure State hand. No choice for me, no choice for the Chancellor.",
    'The odds finally caught up with us. Not a single Civil card in sight.',
    "The deck's bias towards the State was total this round.",
    "I passed on the State because there was nothing else to pass.",
    'A total washout of Civil directives. We are at the mercy of the draw.',
    "The draw was a symphony of State directives. I am just the conductor.",
    "Zero options for the Charter. My hands were tied by the cards.",
    "The Secretariat is having a dark round. Triple State cards.",
    "I looked for a Civil card. I found none. The draw was absolute.",
    "The draw was entirely comprised of State directives. Unfortunate.",
    "Not a single lick of Civil logic in that hand. All State.",
    "The Secretariat's draw was a monochrome of State directives.",
    "I am as disappointed as anyone. The deck is definitely against us.",
  ],
  // After a failed government vote
  governmentFailed: [
    'A wasted session. We cannot keep stalling the Secretariat.',
    'Deadlock serves no one here. The Crisis does not wait.',
    'We need to form a functional government. Now.',
    'The Assembly is divided. This is dangerous.',
    'Another failed vote. The State grows stronger with every delay.',
    'We are running out of time.',
    'Stalling only helps the State.',
    'We must come to an agreement.',
    'This deadlock is unacceptable.',
    'The Assembly is failing us.',
    'We are paralyzed. This is exactly what the State wants.',
    'Every failed vote is a victory for our enemies.',
    "The Assembly's indecision is our greatest weakness.",
    'We must find common ground or face the consequences.',
    'This obstructionism is destroying the Charter.',
    'The Crisis is deepening while we argue.',
    'We cannot afford another round of failure.',
    'The State is laughing at our division.',
    'We need leadership, not deadlock.',
    'The Assembly is spinning its wheels.',
    "Every 'Nay' vote is a pulse of life for the State's ambitions.",
    "We are bickering while the Charter burns. Form a government!",
    "This indecision is a death sentence for the Assembly.",
    "The Secretariat despises a vacuum. We must fill it with leadership.",
    "Are we here to debate or to enact the Charter? Form a government.",
    "The State thrives in the shadows of our disagreement.",
    "Another failed attempt. We are becoming as weak as our enemies.",
    "The Assembly's lack of unity is its own undoing.",
    "We are handing the State the upper hand through our own division.",
    "A government of straw is better than no government at all.",
    "The Crisis only intensifies while we stall. Make a choice!",
    "The Secretariat is growing impatient with our paralysis.",
    "Obstructionism is a slow poison for the Charter.",
    "We are arguing over titles while the building burns around us.",
  ],
  // After investigation — Civil result
  investigateCivil: [
    'The investigation confirms their alignment, {name} is Civil.',
    'Nothing of concern found. {name} is Charter-loyal.',
    '{name} appears to stand with the Assembly.',
    "I've cleared {name}. They are one of us.",
    'My findings on {name} are positive. They support the Charter.',
    '{name} is definitely on our side.',
    'I trust {name} completely.',
    'The investigation was successful. {name} is Civil.',
    '{name} is a true ally.',
    "I have verified {name}'s loyalty.",
    "I've looked into {name} and found a loyal citizen.",
    'Nothing of concern found. {name} is Charter-loyal.',
    'My report on {name} is entirely positive.',
    "I'm happy to report that {name} is Civil.",
    '{name} has my full confidence after this investigation.',
    "The data confirms {name}'s loyalty.",
    "I've verified that {name} is on our side.",
    '{name} is a solid ally for the Charter.',
    'No State influence detected in {name}.',
    "I stand by {name}'s Civil alignment.",
    "My investigation into {name} was exhaustive. They are clean.",
    "The data stream is clear: {name} is a citizen of the Charter.",
    "I've cleared {name} of all suspicion. They are one of us.",
    "{name}'s record is a testament to Civil duty.",
    "I found nothing but loyalty in {name}'s profile.",
    "{name} is a beacon of Civil hope in this investigation.",
    "My report on {name} is glowing. They are authentically Civil.",
    "I have verified {name}'s adherence to the Charter protocols.",
    "There is no trace of State influence in {name}'s recent history.",
    "{name} has passed every loyalty test I administered.",
    "I'm satisfied with {name}'s alignment. They are definitely Civil.",
    "The investigation confirms that {name} stands for the Assembly.",
    "{name}'s record is as clear as a sunny day at the Secretariat.",
    "I would vouch for {name}'s Civil alignment under oath.",
  ],
  // After investigation — State result
  investigateState: [
    'The investigation confirms their alignment, {name} is State.',
    'The investigation is… troubling. Watch {name} closely.',
    'I have learned something critical about {name}. Proceed with caution.',
    "{name}'s allegiance is not to the Charter.",
    "I cannot trust {name} after what I've seen.",
    'The evidence against {name} is damning.',
    '{name} is a threat to the Charter.',
    "I've uncovered {name}'s true colors.",
    'Watch out for {name}.',
    "The investigation revealed {name}'s treachery.",
    '{name} is not who they say they are. They are State.',
    "I've found evidence of {name}'s State ties.",
    'The investigation into {name} was a wake-up call.',
    '{name} is a sleeper agent for the State.',
    'I cannot in good conscience trust {name} anymore.',
    'The truth about {name} is out: they are State.',
    '{name} is working against us from within.',
    "I've seen enough to know {name} is a traitor.",
    'The investigation into {name} revealed a dark secret.',
    'Be warned: {name} is a State operative.',
    "The investigation of {name} was a descent into State treachery.",
    "I found evidence in {name}'s records that will shock the Assembly.",
    "{name} is a wolf in Civil clothing. They are State.",
    "The investigation confirms my worst fears about {name}.",
    "I have uncovered a web of State ties connected to {name}.",
    "{name} is a danger to everything the Charter stands for.",
    "My investigation into {name} was a revelation of betrayal.",
    "The data doesn't lie: {name} is a State operative.",
    "I found proof of {name}'s collaboration with our enemies.",
    "{name} is not who they claim to be. They are a State agent.",
    "The investigation into {name} revealed a pattern of State-led sabotage.",
    "I cannot emphasize this enough: {name} is State-aligned.",
    "{name} has been compromised by the State's influence.",
    "The evidence against {name} is indisputable. They are State.",
  ],
  // Suspicious nomination comment (Civil AI)
  suspiciousNominee: [
    'Interesting choice of Chancellor.',
    'I will be monitoring this government carefully.',
    'That nomination raises questions within the Secretariat.',
    "I'm not sure {name} is the right person for this role.",
    'Why {name}? There are more trustworthy options.',
    "I don't like this nomination.",
    'This government seems suspicious.',
    "I'm keeping a close eye on {name}.",
    'I have my doubts about this choice.',
    'This nomination is questionable.',
    'I have my reservations about {name} as Chancellor.',
    'Is {name} really the best we can do?',
    'This nomination feels like a calculated risk.',
    "I'm sensing a pattern here that I don't like.",
    "{name} hasn't exactly earned our trust yet.",
    'This choice of Chancellor is... unexpected.',
    "I'm not convinced {name} is the right fit.",
    "There's something off about this nomination.",
    "I'd like to hear more from {name} before we vote.",
    'This nomination is a bit too convenient for some.',
    "I'm not the only one who finds this government pairing suspicious.",
    "The nomination of {name} feels like a strategic move for the State.",
    "I sense a hidden agenda behind the choice of {name}.",
    "Why this specific government? Why {name} right now?",
    "This nomination seems designed to further the State's goals.",
    "I have serious doubts about the motivations behind this pair.",
    "The alignment of this government is... questionable at best.",
    "I'm worried this nomination is a step towards State dominance.",
    "The choice of {name} as Chancellor should concern everyone here.",
    "I smell a rat in this nomination process.",
    "This government seems too perfectly aligned with State interests.",
    "I have my misgivings about this specific power dynamic.",
    "{name}'s presence in this government is a red flag.",
    "I'm not comfortable with the potential influence of this pairing.",
  ],
  // High suspicion comments
  highSuspicion: [
    'I have a very bad feeling about {name}.',
    '{name} is acting against the interests of the Assembly.',
    'The data suggests {name} is not who they claim to be.',
    "We need to marginalize {name} before it's too late.",
    "I'm calling it out: {name} is working for the State.",
    '{name} is a traitor.',
    "I'm certain {name} is State.",
    'We need to get rid of {name}.',
    "Don't trust {name} under any circumstances.",
    '{name} is sabotaging us.',
    "I'm 99% sure {name} is a State agent.",
    'The evidence against {name} is mounting.',
    "We can't let {name} near the Chancellor's seat.",
    '{name} is a clear and present danger to the Charter.',
    "I've seen {name} sabotage us before.",
    "Don't let {name}'s words fool you; they are State.",
    'The Assembly must unite against {name}.',
    '{name} is a cancer in this room.',
    "I'm calling for an immediate investigation of {name}.",
    '{name} is the enemy within.',
    "{name}'s betrayal is a stain on the Assembly's history.",
    "We are witnessing the slow destruction of the Charter by {name}.",
    "The State has found its champion in {name}. We must act.",
    "I'm calling for the immediate removal of {name} from all authority.",
    "{name} has shown their true colors, and they are the colors of the State.",
    "The evidence against {name} is beyond reproach. They are a traitor.",
    "We cannot afford to let {name} continue their sabotage.",
    "{name} is a parasite feeding on the weakness of the Assembly.",
    "I'm exposing {name} for what they are: a double agent for the State.",
    "{name}'s actions are a direct assault on the principles of the Charter.",
    "The time for doubt is over. {name} is definitely our enemy.",
    "We must isolate {name} before they destroy us from within.",
    "The State's influence is clear in every move {name} makes.",
    "I will not rest until {name} is held accountable for their treachery.",
  ],
  // Defending self
  defendingSelf: [
    'My record is clear. I serve the Charter.',
    'Do not let suspicion cloud your judgment. I am Civil.',
    'The accusations against me are baseless distractions.',
    "I have only ever worked for the Assembly's success.",
    'Look at the facts, not the rumors. I am loyal.',
    'I have nothing to hide.',
    'My loyalty to the Charter is unwavering.',
    'I am being framed.',
    'The accusations are false.',
    'I am as Civil as they come.',
    "My actions have always been in the Charter's interest.",
    'I am being targeted because I am a threat to the State.',
    "Don't believe the lies being spread about me.",
    'I have a long history of serving the Assembly faithfully.',
    'I am a victim of a State-led smear campaign.',
    'My loyalty is beyond question.',
    'I will prove my innocence through my actions.',
    'The State wants you to doubt me.',
    'I am a true believer in the Charter.',
    'I will not be intimidated by these false claims.',
    "My loyalty to the Charter is my only master. I am Civil.",
    "Don't let these coordinated lies distract you from my record.",
    "I have sacrificed much for the Assembly. My alignment is clear.",
    "The State wants you to see me as an enemy because I am a threat to them.",
    "I invite any investigation. My records are an open book for the Charter.",
    "I am as Civil as the laws themselves. My actions will prove it.",
    "The accusations against me are a thin veil for State aggression.",
    "I stand by the Charter, even when the rest of you doubt me.",
    "I have only ever worked to safeguard our path within the Secretariat.",
    "My conscience is clear. I serve the Assembly, not the State.",
    "These attacks are meant to weaken my resolve. They will not succeed.",
    "I am a true patriot. Do not let these baseless rumors sway you.",
    "I have fought for the Charter when others remained silent.",
    "My commitment to the Civil cause is beyond any interrogation.",
  ],
  // Praising someone as Civil
  praisingCivil: [
    'I trust {name}. Their actions speak for themselves.',
    '{name} has proven their loyalty to the Assembly.',
    'We need more people like {name} in power.',
    "I'm confident in {name}'s alignment.",
    '{name} is a true patriot of the Charter.',
    '{name} is a great leader.',
    'I fully support {name}.',
    '{name} is doing a great job.',
    'We can count on {name}.',
    '{name} is a beacon of hope for the Assembly.',
    "I've always known {name} was a true patriot.",
    "I've seen {name} make the hard choices for the Charter.",
    'We are lucky to have {name} on our side.',
    '{name} is a model of Civil virtue.',
    'I would trust {name} with my life.',
    '{name} is the kind of leader we need right now.',
    '{name} is a pillar of the Assembly.',
    '{name} is a true asset to this room.',
    'I have nothing but respect for {name}.',
    'The Assembly is stronger with {name} in it.',
    "{name}'s dedication to the Charter is an inspiration to us all.",
    "We would do well to follow {name}'s lead in this matter.",
    "{name} is a shining example of what it means to be truly Civil.",
    "I have complete faith in {name}'s judgment and character.",
    "{name} is a steady hand in these turbulent times for the Assembly.",
    "I stand firmly beside {name} in our shared mission for the Charter.",
    "{name} is one of the few here who truly understands our duty.",
    "The Secretariat is fortunate to have a servant as loyal as {name}.",
    "{name} has consistently demonstrated their commitment to our cause.",
    "I hold {name} in the highest regard as a fellow patriot.",
    "We are safer with {name} in a position of authority.",
    "{name} is a true champion of the Civil principles we hold dear.",
    "I would trust {name}'s judgment even in the darkest of rounds.",
    "{name}'s loyalty is the bedrock upon which the Assembly should build.",
  ],
  // Early game support when no actions have occurred
  neutralSupport: [
    "I'm willing to give {name} a chance.",
    '{name} seems like a reasonable choice for now.',
    "Let's see what {name} can do.",
    "I don't have any reason to doubt {name} yet.",
    'A fresh start with {name} might be what we need.',
    "I'm neutral on {name} for now.",
    "Let's see how {name} performs.",
    "I'm open to {name}'s nomination.",
    "I'm not sure about {name} yet.",
    "I'll wait and see with {name}.",
    "Let's give {name} the benefit of the doubt for now.",
    '{name} deserves a chance to prove themselves.',
    "I'm cautiously optimistic about {name}.",
    "I'll support {name} until they give me a reason not to.",
    '{name} seems like a safe bet for this round.',
    "I'm willing to work with {name}.",
    "Let's see if {name} can lead us effectively.",
    "I'm keeping an open mind about {name}.",
    "{name} is an unknown quantity, but I'll vote Aye.",
    "I'm okay with {name} for this government.",
    "{name} seems like a stable choice for this point in the round.",
    "I'm prepared to support {name}'s nomination as a bridge-builder.",
    "{name} hasn't given us any reason to doubt them yet, let's proceed.",
    "A nomination of {name} seems logical given our current state.",
    "I'm voting 'Aye' for {name} based on their performance so far.",
    "{name} is a reasonable candidate to lead this government.",
    "I'm willing to overlook my initial doubts about {name} for now.",
    "{name} has been relatively consistent in their Civil rhetoric.",
    "I'm optimistic that {name} will act in the best interests of the Charter.",
    "Let's move forward with {name} and see where it takes us.",
    "I'm giving {name} the benefit of the doubt this round.",
    "{name} seems to be a pragmatic choice for the current climate.",
    "I'm supporting {name} in the interest of breaking this deadlock.",
    "{name} has earn a shot at leading the next directive cycle.",
  ],
  // General game banter
  banter: [
    'The stakes are rising. We must stay vigilant.',
    'The Secretariat is watching us all.',
    'One wrong move and the Charter falls.',
    'Trust is a rare commodity in these times.',
    "Let's focus on the directives. The Assembly depends on us.",
    'The State is always watching.',
    'We must be careful.',
    'The Assembly is in danger.',
    'We need to be smarter.',
    'The State is closing in.',
    'The shadows are lengthening over the Assembly.',
    'We are the last line of defense for the Charter.',
    'Every decision we make echoes in the Secretariat.',
    "The State's reach is long, but our resolve is strong.",
    'In this room, even the walls have ears.',
    'The future of the Charter is in our hands.',
    'We must be the light in the darkness.',
    "The State's victory is not inevitable.",
    'We are the guardians of the Assembly.',
    'The Charter will prevail if we stay united.',
    "The Secretariat doesn't deal in certainty, only probability.",
    "We are all just players in a game we don't fully understand.",
    "The State is a predator that never sleeps. We must be ready.",
    "Silence is often the loud cry of a State operative.",
    "The Assembly is a delicate machine. One broken gear can ruin it all.",
    "The shadows of the past are catching up with the Secretariat.",
    "Trust is a luxury we can ill afford in this climate of suspicion.",
    "The Charter is a promise that only we can keep.",
    "The State is a mirror reflecting our own weaknesses back at us.",
    "Every round is a battle for the soul of the Assembly.",
    "We are living in an era of unprecedented crisis. Vigilance is keyword.",
    "The Secretariat's record will show who among us was truly loyal.",
    "The path to victory is paved with the courage to call out the State.",
    "We are the architects of the future, or the gravediggers of the past.",
  ],
  // Power usage
  powerUsage: [
    "I am using my power to ensure the Assembly's success.",
    'This power is necessary to protect the Charter.',
    'I must use this power to uncover the truth.',
    'The situation demands this action.',
    'I am using this power to secure our future.',
    'This is the only way to proceed.',
    'I am using this power for the good of the Assembly.',
    'This power will help us identify the threats.',
    'I have no choice but to use this power.',
    'I am using this power to strengthen our position.',
    'I am exercising my authority for the stability of the room.',
    'This action is mandated by the current emergency.',
    'I am using this power to protect our collective interests.',
    'The Charter allows for this measure in times of crisis.',
    'I am taking this step to ensure the State does not gain ground.',
    "This is a necessary use of my title's power.",
    'I am acting to preserve the integrity of the Assembly.',
    "This power is a tool for the Charter's defense.",
    'I am using this ability to clarify the situation.',
    "I am using this power to uphold the Charter's principles.",
    "My title's authority is being exercised to secure our collective safety.",
    "This ability is a necessary intervention for the good of the Assembly.",
    "I am using this power to clarify the path ahead for the Charter.",
    "The situation has deteriorated enough to warrant this action.",
    "I am using this authority to ensure the State does not prevail.",
    "This is a duty I perform with no pleasure, but entire commitment.",
    "I am taking this step to protect the innocent and expose the guilty.",
    "My power is a shield for the Charter, and I am using it now.",
    "This intervention is designed to stabilize our crumbling democracy.",
    "I am using this ability to prevent a total collapse into State control.",
    "The Secretariat mandates this action in the face of such uncertainty.",
    "I am acting to ensure the long-term survival of the Assembly.",
    "This power is a burden I carry for all of you. It must be used.",
    "I am using this authority to bring clarity to a room clouded by doubt.",
  ],
} as const;

